// *** Created By Isuru B. Ranapana *** //
// ***     Eyepax IT Consulting     *** //
// ***   on 12/19/2022 => 12:45 PM  *** //

const StringUtils = {
    IMAGE_SLIDER : 'IMAGE SLIDER',
    CUSTOM_PAINTER: 'CUSTOM PINTER',
    IMAGE_PICKER: 'IMAGE PICKER',
    ANIMATION: 'ANIMATION',
    BIOMETRICS: 'BIOMETRICS',
    ANIMATED_DRAWER: 'ANIMATED DRAWER',
    BOTTOM_NAVIGATION:'BOTTOM NAVIGATION',
    ANIMATED_BOTTOM_NAVIGATION:'ANIMATED BOTTOM NAVIGATION',
    SCROLL_BOTTOM_NAVIGATION: 'SCROLL BOTTOM NAVIGATION',
    FANCY_BOTTOM_NAVIGATION: 'FANCY BOTTOM NAVIGATION',
    STANDARD_DRAWER_NAVIGATION: 'STANDARD DRAWER NAVIGATION',
    VOICE_COMMAND:'VOICE COMMAND',
    ON_BOARDING:'ON BOARDING',
    BOTTOM_TAB_NAVIGATOR:'BOTTOM TAB NAVIGATOR',
    BOTTOM_SHEET:'BOTTOM SHEET',
};

export default StringUtils;

